from sqlalchemy.sql.sqltypes import Integer, String, Date
from DB.database import Base
from sqlalchemy import Column

#Creation table in the DB
class DbUser(Base):
  __tablename__ = 'users'# define table name
  # id will be primary key and generated by automatically
  id = Column(Integer, primary_key=True, index=True)
  username = Column(String)
  email = Column(String)
  password = Column(String) #password will be hashed
  first_name = Column(String) 
  last_name = Column(String)